apiVersion: v1
kind: Namespace
metadata:
  name: harborsync-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-web
  namespace: harborsync-demo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: demo-web
  template:
    metadata:
      labels:
        app: demo-web
    spec:
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: demo-web
      containers:
        - name: nginx
          image: nginx:1.28.0-alpine
          ports:
            - name: http
              containerPort: 80
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 5
          resources:
            requests:
              cpu: 25m
              memory: 32Mi
            limits:
              cpu: 200m
              memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: demo-web
  namespace: harborsync-demo
spec:
  selector:
    app: demo-web
  ports:
    - name: http
      port: 80
      targetPort: http
