apiVersion: v1
kind: Namespace
metadata:
  name: harborsync
---
apiVersion: v1
kind: Secret
metadata:
  name: harborsync-runtime
  namespace: harborsync
  labels:
    app.kubernetes.io/part-of: harborsync
type: Opaque
stringData:
  POSTGRES_USER: harbor
  POSTGRES_PASSWORD: harbor123
  RABBITMQ_DEFAULT_USER: harborsync
  RABBITMQ_DEFAULT_PASS: harborsync123
  HARBORSYNC_JWT_SECRET: harborsync-demo-jwt-secret
