global_defs {
    router_id K8S_MASTER2
    enable_script_security
    script_user root
}

vrrp_script chk_haproxy {
    script "/usr/local/bin/check_haproxy.sh"
    interval 2
    timeout 2
    fall 2
    rise 2
    weight -30
}

vrrp_instance VI_K8S_API {
    state BACKUP
    interface ens18
    virtual_router_id 51
    priority 140
    advert_int 1
    unicast_src_ip 192.168.10.137
    unicast_peer {
        192.168.10.136
        192.168.10.138
    }
    authentication {
        auth_type PASS
        auth_pass CHANGE_ME_VRRP_PASS
    }
    virtual_ipaddress {
        192.168.10.150/24 dev ens18
    }
    track_script {
        chk_haproxy
    }
}

vrrp_instance VI_HARBORSYNC_INGRESS {
    state BACKUP
    interface ens18
    virtual_router_id 52
    priority 140
    advert_int 1
    unicast_src_ip 192.168.10.137
    unicast_peer {
        192.168.10.136
        192.168.10.138
    }
    authentication {
        auth_type PASS
        auth_pass CHANGE_ME_VRRP_PASS
    }
    virtual_ipaddress {
        192.168.10.151/24 dev ens18
    }
    track_script {
        chk_haproxy
    }
}
